name: "release"
on:
  push:
  #  branches:
    tags:
      - '*'
  #pull_request:
  #  branches:
  #    - '*'

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Ninja
        uses: ashutoshvarma/setup-ninja@v1.1

      - name: Configure CMake
        run: cmake -G "Ninja" -B build

      - name: Build
        run: cmake --build build

      - uses: actions/upload-artifact@v3
        with:
          name: linux-release
          path: build/modlimitfix

  windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Ninja
        uses: ashutoshvarma/setup-ninja@v1.1

      - name: Configure CMake
        #run: cmake -G "Visual Studio 17 2022" -B build
        run: cmake -G "Ninja" -B build

      - name: Build
        run: cmake --build build

      - uses: actions/upload-artifact@v3
        with:
          name: windows-release
          path: build/modlimitfix.exe

  release:
    runs-on: ubuntu-latest
    needs: [linux, windows]

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          draft: true
          generateReleaseNotes: true
          artifacts: "modlimitfix,modlimitfix.exe"
          token: ${{ secrets.GITHUB_TOKEN }}